### ISSUE TITLE
passing a parameter with type YSON

### ISSUE THREAD

**Issue by levcom** [ydb-platform/ydb-rs-sdk#168]
When passing a parameter with type YSON, the server returns the following error

 Invalid value representation for type: Yson, expected value case: 8, but current: 9\

Ex:

    let tst_query = "DECLARE $p AS YSON; \
    SELECT $p";

    t.query(
                Query::new(tst_query).with_params(ydb_params!("$p" => Value::Yson("[]".to_string()))),
            ).await?

**Comment by rekby** [comment]
The issue have been fixed in 0.7.0 version, now you have to use bytes for create yson value and bytes will send to a server for fix the error.
