### ISSUE TITLE
Is Ydb platform ydb-rs-sdk stalled? 

### ISSUE THREAD

**Issue by makorne** [ydb-platform/ydb-rs-sdk#181]
I posted [a serious bug](https://github.com/ydb-platform/ydb-rs-sdk/issues/180)  3 days ago..
Nobody answered to it.

As  was written here 2 years ago:
[If you know existed good migration tool - better add YDB support to it](https://github.com/ydb-platform/ydb-rs-sdk/issues/53#issuecomment-1129685822)

But almost every in the rust world knows that this tool - [sqlx](https://crates.io/crates/sqlx) .

And it was planned to [Add support ydb to sqlx](https://github.com/ydb-platform/ydb-rs-sdk/issues/54#issuecomment-1131299935)
2 years ago!! 

And still nothing changed!

Ask your bosses:  will  users  have to wait for basic migration tools for 5, 10 or 20 years? 
But users will lose interest in a so slowly developed sdk!
May be bosses can find enough developers for normal developing speed? 

The [unoficial one-man project](https://github.com/bool-rus/ydb-unofficial) alone did migrations, pools and many of these useful things: 

```
YQL Query for data (like DML)
YQL Query for sheme (like DDL)
Connect over grpcs (with tls)
Connect over grpc (without tls) - not worked, unknown cause
Connection pool (with [deadpool](https://crates.io/crates/deadpool)) (feature pool)
Token authentication
Service account key authentication (feature auth-sa)
Metadata authentication
Query helpers (a lot of)
[sqlx](https://crates.io/crates/sqlx) integration - partially done (feature sqlx):

    Connection string
    connection
    binding parameters
    preparing statements
    transaction manager
    DML (data) operations
    DDL (scheme) operations
    primitive types (bool, i8, i32, i64, u8, u32, u64, f32, f64, Vec<u8>, String)
    date types (Date, Datetime, Timestamp, Interval)
    Decimal type
    connection pool balancing for discovery
    compile-time checked queries
    migrations
    multiple transaction modes
    log statements
    operation parameters
```

Why can't a commercial platform develop even at the same speed as one man writing for free in his free time?

**Comment by rekby** [comment]
Hello.

Thanks for your feedback. It is important for us.

> I posted https://github.com/ydb-platform/ydb-rs-sdk/issues/180 3 days ago..
Nobody answered to it.

It isn't a bug. You can configure timeouts with standard tokio's way: use [timeouts](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html). I agree about examples can be better.


We are working on the SDK, for example we have added support of new auth type and coordination service some time ago.
