### ISSUE TITLE
Tools for migration scheme

### ISSUE THREAD

**Issue by avkviring** [ydb-platform/ydb-rs-sdk#53]
@rekby  Are you planning support migration? 
I want do it, but I can do it in separated project or in this project. Whats way is better?

P.S. Sorry for my Englisch :-(

**Comment by rekby** [comment]
SDK is low-level code and will not support migration inside the project by design.

If you know existed good migration tool - better add YDB support to it, or do it as separate project.

> P.S. Sorry for my Englisch :-(

Don't worry - It's ok.
